
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 07 17:53:31 CET 2022
//----------------------------------------------------

package mini_c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 25;
  public static final int SIZEOF = 11;
  public static final int SEMICOLON = 29;
  public static final int ELSE = 8;
  public static final int IDENT = 2;
  public static final int PLUS = 23;
  public static final int STRUCT = 6;
  public static final int INT = 5;
  public static final int EQUAL = 17;
  public static final int LP = 12;
  public static final int AMPAMP = 19;
  public static final int WHILE = 9;
  public static final int RP = 13;
  public static final int NOT = 28;
  public static final int RBRA = 15;
  public static final int RETURN = 10;
  public static final int IF = 7;
  public static final int LBRA = 14;
  public static final int AMP = 20;
  public static final int COMMA = 16;
  public static final int EOF = 0;
  public static final int CMP = 4;
  public static final int DIV = 26;
  public static final int BARBAR = 18;
  public static final int MINUS = 24;
  public static final int ARROW = 27;
  public static final int error = 1;
  public static final int EQ = 21;
  public static final int INTEGER = 3;
  public static final int NEQ = 22;
  public static final int UMINUS = 30;
}

